name: Build and publish to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build pages
      run: make
    - name: Configure GitHub Pages
      uses: actions/configure-pages@v3
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'target'

  publish:
    permissions:
      contents: read
      pages: write
      id-token: write
    needs: build
    environment:
      name: github-pages
      url: $
    runs-on: ubuntu-latest
    steps:
    - name: Publish to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v3
